apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-k8s-proxy
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-k8s-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: sa-k8s-proxy
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: svc-k8s-proxy
spec:
  type: ClusterIP
  selector:
    app: app-k8s-proxy
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-k8s-proxy
spec:
  selector:
    matchLabels:
      app: app-k8s-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: app-k8s-proxy
    spec:
      serviceAccountName: sa-k8s-proxy
      containers:
      - name: k8s-proxy
        image: 172.100.100.134/vvv/k8s-proxy:TAG
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"